GET http://localhost:5050/api/admin/routes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIyYTE0NDRlOC1jNzFhLTRlZWItODczMS02MjFjN2YyNzRjMmQiLCJSYW5kb21Db29raWUiOiJnWllDQVEvVHVybVUiLCJBcHBsaWNhdGlvbklkIjoiYzE2YmJkYWItZDM5Zi00M2QyLWIzNDUtZGFkNDQ4ODQ2MTdmIiwiQWRtaW5pc3RyYXRvciI6IlRydWUiLCJhdWQiOlsibW91bnRhaW4tYWRtaW4uZGF0aXZlLWdwaS5jb20iLCJtb3VudGFpbi5kYXRpdmUtZ3BpLmNvbSJdLCJuYmYiOjE2OTI4MDY0ODMsImV4cCI6MTY5MjgxMDA4MywiaXNzIjoiZGF0LXByb2R1Y3QifQ.ddB1BR6I7YweOkKudqcw581ZegipcgcVLQIVNgoV5YM

###

GET http://localhost:5050/api/translations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIyYTE0NDRlOC1jNzFhLTRlZWItODczMS02MjFjN2YyNzRjMmQiLCJSYW5kb21Db29raWUiOiJnWllDQVEvVHVybVUiLCJBcHBsaWNhdGlvbklkIjoiYzE2YmJkYWItZDM5Zi00M2QyLWIzNDUtZGFkNDQ4ODQ2MTdmIiwiQWRtaW5pc3RyYXRvciI6IlRydWUiLCJhdWQiOlsibW91bnRhaW4tYWRtaW4uZGF0aXZlLWdwaS5jb20iLCJtb3VudGFpbi5kYXRpdmUtZ3BpLmNvbSJdLCJuYmYiOjE2OTI4MDY0ODMsImV4cCI6MTY5MjgxMDA4MywiaXNzIjoiZGF0LXByb2R1Y3QifQ.ddB1BR6I7YweOkKudqcw581ZegipcgcVLQIVNgoV5YM
