openapi: 3.0.0
info:
  title: XXXXX
  description: Extension XXXXX pour Dat'Foundation
  version: 0.0.

servers:
  - url: hhtps://localhost:5001/api/v1
    description: Serveur de test local

paths:
  /token:
    get:
      summary: Récupère un token signé pour un utilisateur particulier en échange d'un token signé générique
      description: Retourne un Jwt signé par l'extension qui sera transmis à l'Iframe de l'extension par le front pour réaliser des requêtes vers le back
      operationId: getToken
      responses : 
        '200':
          description: Requête réussie, un Jwt est retourné
          content: 
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Le token signé par l'extension
        '400':
          description: Mauvaise requête
          content: 
            text/plain:
              schema:
                type: string
                description: Le message d'erreur
        '404':
          description: Rien à l'adresse indiquée
          content: 
            text/plain:
              schema:
                type: string
                description: Le message d'erreur
        '500':
          description: Erreur serveur
          content: 
            text/plain:
              schema:
                type: string
                description: Le message d'erreur
